name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
analytics.identify("userId", {
  "city": "<<type: string>>",
  "country": "<<type: string>>",
  "postal_code": "<<type: string>>",
  "state": "<<type: string>>",
  "street": "<<type: string>>",
  "age": "<<type: number>>",
  "avatar": "<<type: string>>",
  "birthday": "<<type: Date>>",
  "company_name": "<<type: string>>",
  "company_id": "<<type: string>>",
  "company_employee_count": "<<type: string>>",
  "company_plan": "<<type: string>>",
  "created_at": "<<type: string>>",
  "description": "<<type: string>>",
  "email": "<<type: string>>",
  "first_name": "<<type: string>>",
  "gender": "<<type: string>>",
  "id": "<<type: string>>",
  "last_name": "<<type: string>>",
  "name": "<<type: string>>",
  "phone": "<<type: string>>",
  "title": "<<type: string>>",
  "username": "<<type: string>>",
  "website": "<<type: string>>"
});
